script: 'ci/travis.rb'
rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0
  - jruby-head
  - rbx-2
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk7
gemfile:
  - Gemfile
notifications:
  email:
    recipients:
      - Martin.Bosslet@gmail.com
    on_success: always
    on_failure: always
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - jdk: openjdk7
      rvm: ruby-head
      rvm: 2.2
      rvm: 2.1
      rvm: 2.0
      rvm: rbx-2
    - jdk: oraclejdk7
      rvm: ruby-head
      rvm: 2.2
      rvm: 2.1
      rvm: 2.0
      rvm: rbx-2

